### ISSUE TITLE
(fix): Only Deploy on master branch

### ISSUE THREAD

**Issue by crh225** [crh225/angular-github-issues#185]
change circle.yml
```
deployment:
  production:
    branch: master
    commands:
        firebase deploy
```
